---

- hosts: sdcgigdcapmdw02
  become: true
  
  vars_prompt:  
    - name: "port"
      prompt: "What is the port?"
      private: no
    - name: "server"
      prompt: "What is the remote server?"
      private: no
  
  roles:
    - checkport
