---

- hosts: all
  become: true
  gather_facts: false


  vars_prompt:  
    - name: "pvname"
      prompt: "What is the physical volume(sdb or vdb or enter)?"
      private: no 
      default: ""   
      
  roles:
    - fdisk-list
