---
- hosts: all
  become: true
  gather_facts: false

  vars_prompt:  
    - name: "vgname"
      prompt: "What is the vgname(mandatory)?"
      private: no  
    - name: "lvname"
      prompt: "What is the lvname(mandatory)?"
      private: no  
    - name: "size"
      prompt: "What is the size(100m or 1g or +100%FREE [mandatory])?"
      private: no        
    - name: "pvlist"
      prompt: "Put the physical volumes separated by comma(/dev/sdb1,/dev/sdb2 or enter)?"
      private: no     
      default: ""       
    - name: "force"
      prompt: "Force(yes/no*)?"
      private: no 
      default: "no"
    - name: "active"
      prompt: "Active(yes*/no)?"
      private: no 
      default: "yes"      
    - name: "option"
      prompt: "Free form option(or enter)?"
      private: no 
      default: ""
       
  roles:
    - lvcreate
