---
- hosts: all
  become: true
  gather_facts: false

  vars_prompt:  
    - name: "vgname"
      prompt: "What is the vgname(mandatory)?"
      private: no  
    - name: "lvname"
      prompt: "What is the lvname(mandatory)?"
      private: no  
    - name: "size"
      prompt: "What is the NEW size(100m or 1g or +100%FREE [mandatory])?"
      private: no        
    - name: "force"
      prompt: "Force(yes/no*)?"
      private: no 
      default: "no"
    - name: "resizefs"
      prompt: "resizefs(yes/no/enter)?"
      private: no 
    - name: "shrink"
      prompt: "shrink(yes/no/enter)?"
      private: no 
    - name: "option"
      prompt: "Free form option(or enter)?"
      private: no 
       
  roles:
    - lvresize
