---
- hosts: all
  become: true
  gather_facts: false
  
  vars_prompt:  
    - name: "pvlist"
      prompt: "Put the physical volume(e.g. /dev/sdb1)?"
      private: no  
     

  roles:
    - pvcheck
