---

- hosts: all
  become: true
  gather_facts: false
  
  vars_prompt:  
    - name: "pvlist"
      prompt: "Put the physical volumes separated by space(/dev/sdb1 /dev/sdb2)?"
      private: no  
      default: ""
    - name: "force"
      prompt: "Force(yes/no*)?"
      private: no 
      default: "no"
      
  roles:
    - pvremove
