---

- hosts: all
  become: true
  gather_facts: false

  vars_prompt:

    - name: "src"
      prompt: "Source tar path(local)?"
      private: no
    - name: "dest"
      prompt: "Destination directory path(remote)?"
      private: no
  
  roles:
    - untar
