---
- hosts: all
  become: true
  gather_facts: false

  vars_prompt:  
    - name: "vgname"
      prompt: "What is the vgname(mandatory) to remove?"
      private: no  
    - name: "force"
      prompt: "Force(yes/no*)?"
      private: no 
      default: "no"
            

  roles:
    - vgremove
